version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/apache/development.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8000:80"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=rootpassword
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_DATABASE=laravel
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=rootpassword
        depends_on:
            - mysql

volumes:
    mysql-data:
